env:
  node: true

extends:
  - 'airbnb-base'

rules:
  no-console: 0
  default-case-last: 0
  default-param-last: 0
  function-call-argument-newline: 0
  grouped-accessor-pairs: 0
  no-constructor-return: 0
  no-dupe-else-if: 0
  no-import-assign: 0
  prefer-regex-literals: 0
  prefer-exponentiation-operator: 0
  no-loss-of-precision: 0
  no-promise-executor-return: 0
  no-restricted-exports: 0
  no-setter-return: 0
  no-unreachable-loop: 0
  no-unsafe-optional-chaining: 0
  no-useless-backreference: 0
  no-nonoctal-decimal-escape: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
